# vim:fileencoding=utf-8:foldmethod=marker
shell fish

font_size 12.5
cursor_trail 1
cursor_shape beam

scrollbar_radius 0.6
scrollbar_gap 0.7

tab_bar_margin_height 10.0 0.0
tab_bar_margin_width 20.0
tab_bar_min_tabs  2
tab_bar_align left
tab_bar_style fade
tab_powerline_style round
tab_fade 0.25 0.75 1 1
tab_title_template [{index}] {title}

window_padding_width 10 10 10 10

background_opacity 1.0

# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMono Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

# BEGIN_KITTY_THEME
include rose-pine.conf
# END_KITTY_THEME
